### ISSUE TITLE
LHC comes with a build in JSON parser

### ISSUE THREAD

**Issue by spape** [marcoroth/shortlook-cli#59]
https://github.com/marcoroth/shortlook-cli/blob/67783e0140954e77b22ac0c765d9db6d03d8dc9a/lib/shortlook/commands/provider.rb#L43

Try

```ruby
LHC.get(url).data.results
```

See: https://github.com/local-ch/lhc#accessing-response-data

Thx for using LHC

**Comment by marcoroth** [comment]
Thanks @spape for suggesting this improvement! Much appreciated 😊
